apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: uat-
replicas:
  - name: go-service
    count: 2
resources:
  - ../../base
configMapGenerator:
  - name: config
    files:
      - config.yaml