apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: sit-
replicas:
  - name: go-service
    count: 1
resources:
  - ../../base
configMapGenerator:
  - name: config
    files:
      - config.yaml